function [ans1,ans2,ans3,ans4,stp,gcf,CR] = initial_dialog()
prompt = {'Lower limit of tilting angle     [-90 to 90 degree]',...
    'Upper limit of tilting angle     [-90 to 90 degree]',...
    'Lower limit of aimming angle     [-180 to 180 degree]',...
    'Upper limit of aimming angle     [-180 to 180 degree]',...
    'Measuring step angle for retriving illuminance     [5, 10(recommended), 15, 30(fast) degree]',...
    'Input Global calibration factor? [No CF = 1, or input a positive number]',...
    'Compression rate? [No: 1, or 2,4(recommended),5,10]'};
dlgtitle = 'User Input'; dims = [1 50];
definput = {'-90','90','-180','180','10','1','4'};
answer = str2double(inputdlg(prompt,dlgtitle,dims,definput));
if isempty(answer)
    ans1 = -90; ans2 = 90; ans3 = -180; ans4 = 180; stp = 10; gcf = 1; CR = 4;
else
    ans1 = answer(1); ans2 = answer(2); ans3 = answer(3); ans4 = answer(4);
    stp = answer(5); gcf = answer(6); CR = answer(7);
end
end